### ISSUE TITLE
 Error: “networkId” is required

### ISSUE THREAD

**Issue by abhilashi** [pooltogether/pooltogether-pool-builder-ui#61]
I'm seeing this on http://localhost:3000/ after `$ yarn dev`

Could someone suggest a work around? Any help greatly appreciated. 

<img width="962" alt="Screenshot 2021-08-15 at 10 18 41 PM" src="https://user-images.githubusercontent.com/4708378/129486084-b2e604ad-ac09-4faa-81cc-1049ef0780cb.png">

**Comment by PierrickGT** [comment]
Hi @abhilashi,
Have your setup [direnv](https://direnv.net/docs/installation.html) and copied the required env variables from `.envrc.example` to `.envrc` ?
https://github.com/pooltogether/pooltogether-pool-builder-ui/blob/master/.envrc.example

**Comment by abhilashi** [comment]
@PierrickGT I did install direnv. Copied too. 

I'm unsure of the values. What are the values we should use when we're connecting to a local node? Which of those environment variables are mandatory? Which can be left blank?

**Comment by abhilashi** [comment]
Here is the full trace:

```

Unhandled Runtime Error
Error: "networkId" is required

Call Stack
validateType
node_modules/@pooltogether/hooks/node_modules/@pooltogether/bnc-onboard/dist/esm/onboard-5bbb486a.js (1628:0)
validateInit
node_modules/@pooltogether/hooks/node_modules/@pooltogether/bnc-onboard/dist/esm/onboard-5bbb486a.js (1671:0)
init$1
node_modules/@pooltogether/hooks/node_modules/@pooltogether/bnc-onboard/dist/esm/onboard-5bbb486a.js (8289:0)
initOnboard
node_modules/@pooltogether/hooks/dist/hooks/useInitializeOnboard.js (194:0)
eval
node_modules/@pooltogether/hooks/dist/hooks/useInitializeOnboard.js (41:0)
Generator.next
<anonymous>
eval
node_modules/@pooltogether/hooks/dist/hooks/useInitializeOnboard.js (8:0)
new Promise
<anonymous>
__awaiter
node_modules/@pooltogether/hooks/dist/hooks/useInitializeOnboard.js (4:0)
getOnboard
node_modules/@pooltogether/hooks/dist/hooks/useInitializeOnboard.js (40:0)
eval
node_modules/@pooltogether/hooks/dist/hooks/useInitializeOnboard.js (60:0)
Generator.next
<anonymous>
eval
node_modules/@pooltogether/hooks/dist/hooks/useInitializeOnboard.js (8:0)
new Promise
<anonymous>
__awaiter
node_modules/@pooltogether/hooks/dist/hooks/useInitializeOnboard.js (4:0)
handleLoadOnboard
node_modules/@pooltogether/hooks/dist/hooks/useInitializeOnboard.js (59:0)
eval
node_modules/@pooltogether/hooks/dist/hooks/useInitializeOnboard.js (64:0)
invokePassiveEffectCreate
node_modules/react-dom/cjs/react-dom.development.js (23487:0)
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js (3945:0)
Object.invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (3994:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (4056:0)
flushPassiveEffectsImpl
node_modules/react-dom/cjs/react-dom.development.js (23574:0)
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js (468:0)
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js (11276:0)
flushPassiveEffects
node_modules/react-dom/cjs/react-dom.development.js (23447:0)
eval
node_modules/react-dom/cjs/react-dom.development.js (23324:0)
workLoop
node_modules/scheduler/cjs/scheduler.development.js (417:0)
flushWork
node_modules/scheduler/cjs/scheduler.development.js (390:0)
MessagePort.performWorkUntilDeadline
node_modules/scheduler/cjs/scheduler.development.js (157:0)
```

**Comment by abhilashi** [comment]
@chuckbergeron any help/pointers greatly apprecited

**Comment by PierrickGT** [comment]
> @PierrickGT I did install direnv. Copied too.
> 
> I'm unsure of the values. What are the values we should use when we're connecting to a local node? Which of those environment variables are mandatory? Which can be left blank?

All the values for wallet connection are mandatory.

**Comment by chuckbergeron** [comment]
@abhilashi This happens specifically when the `NEXT_JS_DEFAULT_ETHEREUM_NETWORK_NAME` is not set properly. What is the value of that in your terminal? You can get it by running `export | grep NETWORK_NAME` in the same terminal instance where you run the next.js server for the Builder app.

**Comment by chuckbergeron** [comment]
.@abhilashi Was able to fix this by setting up a zsh hook for `direnv` https://direnv.net/docs/hook.html
